name: Majkulator CI pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Majkulator/**'
      - '.github/workflows/majkulator-ci.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Majkulator/**'
      - '.github/workflows/majkulator-ci.yml'
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: "${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.shortSha }}"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: GitTools
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      -
        name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
  build:
    runs-on: ubuntu-latest
    needs: calculate-version
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Majkulator
          file: ./Majkulator/Majkulator/Dockerfile
          push: true
          tags: "jurajpaska8/majkulator:${{ needs.calculate-version.outputs.semVer }},jurajpaska8/majkulator:latest"
